name: Run tests
on:
  pull_request:
    paths:
      - .github/**
      - gaugan/**
      - tests.py
      - requirements.txt
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -U pip
          pip install -r requirements.txt
          gdown https://drive.google.com/uc?id=1zs2RPZkLeB5QDRVQtpqUtMwepR_Qfufp
          unzip -q facades.zip
          pytest tests.py -s
